name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  tag:
    required: true
    description: 'only act on issues with this tag'
    default: 'label-gun'
runs:
  using: 'node12'
  main: 'dist/index.js'
