name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
