name: 'Label-gun'
description: 'Manage issue feedback'
author: 'Emiliano Heyns'
inputs:
  token:
    required: true
    description: 'token to post to the issue list'
  label.active:
    required: false
    description: 'only act on issues with this tag'
    default: ''
  label.exempt:
    required: false
    description: 'ignore issues with this tag'
    default: ''
  log-id.label:
    required: false
    description: 'tag issues with missing log ID with this label'
    default: ''
  log-id.regex:
    required: false
    description: 'search for this pattern to detect log ID'
    default: ''
  log-id.message:
    required: false
    description: 'post this comment when log ID is missing'
    default: ''
  log-id.prompt:
    required: false
    description: 'follow-up prompt when log ID remains missing'
    default: ''
  label.awaiting:
    required: true
    description: 'follow-up prompt when log ID remains missing'
    default: 'awaiting-user-feedback'
  no-close:
    required: false
    description: 'comment to post when re-opening message closed by non-collaborator'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
